# Generated by Django 2.1.7 on 2019-03-10 23:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yirmi', '0002_user_is_activated'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='createdby',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
