# Generated by Django 2.1.7 on 2019-03-11 00:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yirmi', '0004_auto_20190311_0352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
