# Generated by Django 2.1.7 on 2019-03-11 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yirmi', '0005_auto_20190311_0356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='deparment',
            new_name='department',
        ),
    ]
